# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_user',
            name='phno',
            field=models.BigIntegerField(),
        ),
    ]
