# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0002_auto_20170808_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='req_user',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
