# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0004_category_type_tender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('prj_name', models.CharField(max_length=50)),
                ('t_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=25)),
                ('prj_desc', models.TextField()),
                ('reg_price', models.IntegerField()),
            ],
        ),
    ]
