# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0005_tender_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tender_request',
            new_name='t_request',
        ),
    ]
