# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0006_auto_20170908_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_type',
            options={'verbose_name_plural': 'Category Type'},
        ),
        migrations.AlterModelOptions(
            name='req_user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='t_request',
            options={'verbose_name_plural': 'Requested Tenders'},
        ),
        migrations.AlterModelOptions(
            name='tender_type',
            options={'verbose_name_plural': 'Tender Type'},
        ),
        migrations.AlterModelOptions(
            name='user_type',
            options={'verbose_name_plural': 'User Type'},
        ),
    ]
