# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0008_auto_20170910_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whos_tender', models.IntegerField()),
                ('tender_id', models.IntegerField()),
                ('org_name', models.CharField(max_length=50)),
                ('org_file', models.FileField(upload_to='C:/Python/Webtechlab/wtech_tender/tendermanagement/static/')),
                ('time', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
