# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0009_bid_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid_request',
            options={'verbose_name_plural': 'Tender Bids'},
        ),
    ]
