# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0010_auto_20170918_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_request',
            name='org_file',
            field=models.FileField(upload_to='C:/Python/Webtechlab/wtech_tender/tendermanagement/static/company_docx/'),
        ),
    ]
