# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0013_auto_20170919_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_details',
            options={'verbose_name_plural': 'Card Details'},
        ),
        migrations.AddField(
            model_name='bid_request',
            name='who_bid_for_it',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
