# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendermanagement', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pwrd', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Admin',
            },
        ),
    ]
